# Configure a default setup of Home Assistant (frontend, api, etc)
# default_config:

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_timezone
  # Customization file
  #customize: !include customize.yaml
  packages: !include_dir_named packages

http:
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  
# Enables configuration UI
config:

updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

frontend:
  javascript_version: latest

# Text to speech
tts:
  - platform: google_translate

ifttt:
  key: !secret ifttt_key

hive: 
  username: !secret hive_username
  password: !secret hive_password

#hue:
#  bridges:
#    - host: !secret hue_bridge
#      allow_unreachable: true
#      allow_hue_groups: false

input_boolean:
  notifications:
    name: Notifications
    initial: on
  test:
    name: Test Automation
    initial: off

ios:

alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.co.uk

group: !include groups.yaml
automation: !include automations.yaml
zone: !include zones.yaml
script: !include_dir_merge_named scripts